# this config file controls the behaviour of agent-types such as langserve, controlling what endpoints are used
kind: agentConfig
apiVersion: v1
default:
  stream: "{stem}/vac/streaming/{vector_name}"
  invoke: "{stem}/vac/{vector_name}"

langserve:
  stream: "{stem}/{vector_name}/stream"
  invoke: "{stem}/{vector_name}/invoke"
  input_schema: "{stem}/{vector_name}/input_schema"
  output_schema: "{stem}/{vector_name}/output_schema"
  config_schema: "{stem}/{vector_name}/config_schema"
  batch: "{stem}/{vector_name}/batch"
  stream_log: "{stem}/{vector_name}/stream_log"

edmonbrain:
  stream: "{stem}/vac/streaming/{vector_name}"
  invoke: "{stem}/vac/{vector_name}"

openinterpreter:
  stream: "{stem}/vac/streaming/{vector_name}"
  invoke: "{stem}/vac/{vector_name}"

crewai:
  stream: "{stem}/vac/streaming/{vector_name}"
  invoke: "{stem}/vac/{vector_name}"